package cpen431.mp.KeyValue;

public enum KVSErrorCode {
	SUCCESS, ERROR_NO_KEY, ERROR_OUT_OF_SPACE, ERROR_OVERLOAD, ERROR_INTERNAL_FAILURE,
	ERROR_UNRECOGNIZED_COMMAND, ERROR_INVALID_KEY_LENGTH, ERROR_INVALID_VALUE_LENGTH, ERROR_UNKNOWN
}
